name: Build Docker image and deploy to the Azure App Service service
on:
  push:
    branches:
      - main
      - NUA-* # FIXME: This needs to be removed before the merge
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: "Docker build and push image"
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.AZURE_ACR_URL }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - run: |
          docker build -t ${{ vars.AZURE_ACR_URL }}/my-site:latest -t ${{ vars.AZURE_ACR_URL }}/my-site:${{ github.SHA }} .
          docker push ${{ vars.AZURE_ACR_URL }}/my-site:latest
          docker push ${{ vars.AZURE_ACR_URL }}/my-site:${{ github.SHA }}
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@v4
      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "${{ vars.AZURE_RESOURCE_GROUP_NAME }}"
          cluster-name: "${{ vars.AZURE_AKS_CLUSTER_NAME }}"
      - name: Setup kubectl
        id: install-kubectl
        uses: azure/setup-kubectl@v3
      - name: Deploy the latest Docker image in the AKS cluster
        run: |-
          kubectl apply -k kubernetes/${{ vars.ENVIRONMENT_NAME }}/
          kubectl set image deployment/my-site-deployment my-site-container=${{ vars.AZURE_ACR_URL }}/my-site:${{ github.SHA }}
    needs: build
