name: Build Docker image and deploy to the Azure AKS cluster
on:
  push:
    branches:
      - main
      - "NUA-*" # FIXME: Remove this line once the pipeline works properly
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: ACR login
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az acr login --registry ${{ vars.ACR_NAME }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ vars.ACR_NAME }}.azurecr.io:latest
            ${{ vars.ACR_NAME }}.azurecr.io:${{ github.SHA }}
  # deploy:
  #   runs-on: ubuntu-latest
  #   environment: production
  #   steps:
  #     - name: Checkout the current git repository
  #       uses: actions/checkout@v4
  #     - name: Set AKS context
  #       id: set-context
  #       uses: azure/aks-set-context@v3
  #       with:
  #         resource-group: "${{ vars.AZURE_RESOURCE_GROUP_NAME }}"
  #         cluster-name: "${{ vars.AZURE_AKS_CLUSTER_NAME }}"
  #     - name: Setup kubectl
  #       id: install-kubectl
  #       uses: azure/setup-kubectl@v3
  #     - name: Deploy the latest Docker image in the AKS cluster
  #       run: |-
  #         kubectl apply -k kubernetes/${{ vars.ENVIRONMENT_NAME }}/
  #         kubectl set image deployment/mysite-deployment mysite-container=${{ vars.ACR_NAME }}.azurecr.io/mysite:${{ github.SHA }}
  #   needs: build
