name: Build Docker image and deploy to the Azure Container Apps service
on:
  push:
    branches:
      - main
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@main
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: "Docker build and push image"
        uses: azure/docker-login@v2
        with:
          login-server: ${{ vars.AZURE_ACR_URL }}
          username: ${{ secrets.AZURE_ACR_USERNAME }}
          password: ${{ secrets.AZURE_ACR_PASSWORD }}
      - run: |
          docker build -t ${{ vars.AZURE_ACR_URL }}/my-site:latest -t ${{ vars.AZURE_ACR_URL }}/my-site:${{ github.SHA }} .
          docker push ${{ vars.AZURE_ACR_URL }}/my-site:latest
          docker push ${{ vars.AZURE_ACR_URL }}/my-site:${{ github.SHA }}
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@v4
      - name: Login via Azure CLI
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      - name: Build and deploy Docker container in Azure Container Apps service
        uses: azure/container-apps-deploy-action@v1
        with:
          acrName: ${{ vars.AZURE_ACR_NAME }}
          containerAppName: ${{ vars.AZURE_CONTAINER_APPS_NAME }}
          resourceGroup: ${{ vars.AZURE_RESOURCE_GROUP_NAME }}
          imageToDeploy: ${{ vars.AZURE_ACR_URL }}/my-site:${{ github.SHA }}
          environmentVariables: |
            "GMAIL_SMTP_SERVER=${{ vars.GMAIL_SMTP_SERVER }}" "GMAIL_SMTP_SERVER_PORT=${{ vars.GMAIL_SMTP_SERVER_PORT }}" "GMAIL_EMAIL=${{ vars.GMAIL_EMAIL }}" "GMAIL_APP_PASSWORD=secretref:gmail-app-password"
    needs: build
