name: Build Docker image and deploy to the DigitalOcean Kubernetes cluster
on:
  push:
    branches:
      - main
      - refactor/* # FIXME: Remove this before merging the PR on the main branch
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@main
      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3
      - name: Install doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Log in to DigitalOcean ACR with short-lived credentials
        run: doctl registry login --expiry-seconds 1200
      - name: Docker build and push image to DigitalOcean ACR
        run: |
          docker build -t ${{ vars.DIGITALOCEAN_ACR_URL }}/my-site:latest -t ${{ vars.DIGITALOCEAN_ACR_URL }}/my-site:${{ github.SHA }} .
          docker push ${{ vars.DIGITALOCEAN_ACR_URL }}/my-site:latest
          docker push ${{ vars.DIGITALOCEAN_ACR_URL }}/my-site:${{ github.SHA }}
  deploy:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Install doctl on the runner
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Save the DigitalOcean Kubernetes kubeconfig configuration with a short-lived credentials
        run: doctl kubernetes cluster kubeconfig save --expiry-seconds 600 ${{ vars.DIGITALOCEAN_DOKS_CLUSTER_NAME }}
      - name: Deploy the latest Docker image in the DigitalOcean Kubernetes cluster
        run: |-
          kubectl apply -k kubernetes/${{ vars.ENVIRONMENT_NAME }}/
          kubectl set image deployment/my-site-deployment my-site-container=${{ vars.DIGITALOCEAN_ACR_URL }}/my-site:${{ github.SHA }}
    needs: build
