name: Complete the validations for the code in a Pull Request (PR)
on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
jobs:
  typescript:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@main
      - name: Run the NPM tsc command
        uses: actions/setup-node@v4
      - run: |
          npm ci
          npm run type-check
  lint:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@main
      - name: Run the NPM lint command
        uses: actions/setup-node@v4
      - run: |
          npm ci
          npm run lint
  test:
    runs-on: ubuntu-24.04
    environment: production
    steps:
      - name: Checkout the current git repository
        uses: actions/checkout@main
      - name: Run the NPM test command
        uses: actions/setup-node@v4
      - run: |
          npm ci
          npx playwright install
          npm run ci:test -- -u
